GET http://localhost:8000/api/products HTTP/1.1

###

POST http://localhost:8000/api/products HTTP/1.1
content-type:application/json

{
  "title": "Test",
  "price": "14.23",
  "description": "test"
}

###

GET http://localhost:8000/api/products/ HTTP/1.1

###

PUT http://localhost:8000/api/products/605aeccd4684a425387cf6ae HTTP/1.1
Content-Type:application/json

{
  "title": "Golden Cat",
  "price": "14000",
  "description": "Male, un-neutered"
}

###

DELETE http://localhost:8000/api/products/605ae8957fe1ad245623d920 HTTP/1.1

###

